### ISSUE TITLE
Question on selector normalization

### ISSUE THREAD

**Issue by caub** [dperini/nwsapi#16]
I wonder why you wouldn't normallize 'more' the selector [there](https://github.com/dperini/nwsapi/blob/master/src/nwsapi.js#L1410-L1413), by uppercasing html tags, and camelCasing svg tags (ex: `Div.foo Path` becoming `DIV.foo path`), so that you don't need `hasMixedNamespace` anymore
ar

Edit: Oh crap, some SVG tags are also HTML ones https://github.com/wooorm/svg-tag-names/blob/master/index.json. that explains

**Comment by dperini** [comment]
@caub there are several reasons apart the one you mention.
One particular to keep in mind is that the case (upper/lower/mixed) of elements `nodeName` and `localName` properties depend on how they were included in the document.

So, here is a list of methods through which the elements may be inserted in the document:

    - through the HTML parser during page load
    - using createElement before or after page load
    - using createElementNS before or after page load
    - using innerHTML (``should`` mimic parser behavior)
and probably by other methods like .cloneNode() and .adoptNode().

**Comment by caub** [comment]
Ahh you're right, for `document.createElementNS('http://www.w3.org/2000/svg', 'pATh')` it won't normalize the nodeName, it's not rendered but still present in the DOM https://jsfiddle.net/crl/bntzcgyq/ 

I posted this after Zirro showed on irc.freenode#jsdom some slow-down of querySelector on huge pages (200k+ elements) due to this `hasMixedNamespace` calls (like 30ms vs <1ms without hasMixedNamespace)

I think it may still be possible to avoid `hasMixdNameSpace` and transform the selector for those tag selection case, and tweak the DOM engine, I'll try to do that in my fork, I think it'll even help for my minimal DOM https://github.com/caub/nwsapi/blob/test/test/unit.js

**Comment by dperini** [comment]
@caub see this HTML gist:

https://gist.github.com/dperini/ccc8e424d923c9bfbd25d4b95519ed32

It seems the problem is bigger than we think. A configuration flag and/or a specific `jsdom` property is the way to go here to maintain performance on pages with hundred of thousands nodes.

We cannot presume pages are always 5-10 Kbytes as in our testing environments.

On top of that users want's to mix lower, upper and mixed case tag names most times without a real reason since there are iframes to keep content in context with different namespaces. But we are not
in charge of saying what is correct and what is wrong.

As an example this > 2Mb single namespace https://tc39.github.io/ecma262/ deserves our attention on performances since the developer doesn't have a different path to solve his performance issues he already did the best by using only one namespace (where all nodeName properties are uppercase).

**Comment by dperini** [comment]
@caub forgot to say that the `hasMixedNamespace()` has already been removed in favor of a configuration flag MIXEDCASE set to false by default.
