### ISSUE TITLE
Full CSS3 namespace support

### ISSUE THREAD

**Issue by bedney** [dperini/nwsapi#19]
nwsapi is a brilliant piece of work - wow!

Is there any interest in adding full CSS3 namespace support? This would include adding support for selectors that contain namespaced prefixes such as:

`*|myelem` (this is actually supported natively by `querySelector`/`querySelectorAll` native methods in browsers)
`myns|*` (unsupported natively)
`myns|myelem` (unsupported natively)
`*[*|myattr]` (supported natively)
`*[myns|*]` (unsupported natively)
`*[myns|myattr]` (unsupported natively)

Note that what I'm asking about here is not solved by the simplistic approach of "just use an escaped `:` character". True namespace support requires being able to resolve namespaces based on the location of the element in the DOM, what namespaces are defined in the markup and how namespace prefixes are associated to a URI.

The `document.evaluate` XPath call provides an example of one way this functionality might be provided. It uses a 'namespace resolver' to assist the call in determining the namespace. See the section "Implementing a User Defined Namespace Resolver" here:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Introduction_to_using_XPath_in_JavaScript#Implementing_a_User_Defined_Namespace_Resolver

I currently use a very old jQuery plugin that provides true namespace support to jQuery, but it hasn't been updated in a long time and is only usable with the jQuery 1.X series. Replacing that with nwsapi would be very nice indeed :-).

Thanks!

**Comment by dperini** [comment]
@bedney 
currently `nwsapi` should supports the same native selectors supported by `querySelector / querySelectorAll`, at least this was the primary objective during development and it passes the following W3C "Web Platform Tests" related to namespaces:

    #any-namespace *|div
    #no-namespace |div
    #no-namespace |*
    #attr-presence [*|TiTlE]

You can see the namespace resolver code from Line 804 to Line 816 and for namespaced attributes from Line 818 to Line 823. Also there are other parts handling syntax validation of namespaced selectors (like regular expressions and environment feature detection).

So, assuming I got your question correctly almost everything you asked is already supported.
Maybe you were tricked by missing documentation about that, thus believing these selectors were not supported, or maybe I am misunderstanding your request. I will amend documentation soon.

Currently `nwsapi` should support CSS3 completely and "Selectors Level 4" almost completely, with very few exceptions like `has()` and `:blank` that are still unsupported by browsers too.

There is support for `matches()` and `closest()` methods, Form Validation pseudo-classes (:valid, :invalid, :in-range, :out-of-range, :indeterminate etc...) and mimics new browsers errors, mangled syntax and other special quirks. It is extremely fast in most cases and is used as the base selector engine in `nodejs / jsdom` headless environments. Should be quite stable and can fully replace / override native selectors API. It has no dependencies and can be loaded asynchronously.

If something is not supported I will accept suggestions and provide a solution in a short time.
If you see some of the namespace syntax does not cover what you need please open an issue with a minimal description and short test that fail using `nwsapi` but works using native browser methods.

Since there is already a newer `nwsapi` 2.1.x branch that is going to be released shortly if something is missing I would be happy to add code for covering new features and/or syntax.

Thank you for the review and possible suggestions.

**Comment by bedney** [comment]
@dperini -

Thank you for reply.

As you pointed out, `nwsapi` does indeed support what `querySelector`/`querySelectorAll` does natively, and that is great - really. What I am asking for, however, is "extended" namespace support. I use XHTML in my pages and believe that the W3C made a mistake in not supporting "fully namespaced XHTML/SVG/etc" in DOM calls such as `querySelector`/`querySelectorAll`. Therefore, while it is possible to use the wildcards (i.e. `*`) with the namespace indicator(`|`) for some forms (as you show above), it is not possible to do other forms, such as:

`myns|myelem` -> return `myelem` elements where the namespace is the same as the namespace aliased to the `myns` prefix
`myns|*` -> returns all elements where the namespace is the same as the namespace aliased to the `myns` prefix
`*[myns|*]` -> Returns all elements that have an attribute whose namespace is the same as the namespace aliased to the `myns` prefix (note: we're discussing the *attribute's* namespace here)
`*[myns|myattr]` -> Returns all elements that have an attribute whose namespace is the same as the namespace aliased to the `myns` prefix and where the attribute name is `myattr` (again, we're discussing the *attribute's* namespace here).

The really old, unmaintained project that retrofitted this capability into jQuery 1.X can be found here:

https://github.com/rfk/jquery-xmlns

Now, I think he made a mistake in his API in that you supplied prefix to namespace mappings on the `$.xmlns` object as simple key/value pairs. A more powerful option, and one I recommend, is to do what the W3C did for the `document.evaluate` call for XPath as I described above where you can pass a "namespace resolver" *function* which provides a lot more power in resolving namespaces.

I would definitely be willing to work with you on this, starting with writing some tests, if you would be interested :-).

Thank you for continuing this work!

**Comment by Zirro** [comment]
Whether @dperini is interested in working on it or not, I'd just like to request that any non-standard selector support be disabled by default since we use NWSAPI in [jsdom](https://github.com/jsdom/jsdom) where we try to follow the standard as closely as possible.

NWSAPI also has support for adding custom selectors, so you could potentially look into writing a module like these: https://github.com/dperini/nwsapi/tree/master/src/modules

**Comment by dperini** [comment]
@bedney
without any doubt what @Zirro said is correct, we cannot add non standard functionality that way.

However I forgot to tell about an interesting aspect of `nwsapi` that might come helpful in this case. The engine is modular thus writing an extension may be the way to make everybody happy and maintain non standard functionality in an external module. Currently my spare time is limited but I am willing to help if you wish to take the challenge. In the `modules` directory there is an example extension which adds special `jquery` selectors that can be used as a template on how to write such extension. If you are clear about what the resolver should do on a list of nodes writing such an extension is easy enough.

I believe that some changes will be necessary in the main `nwsapi` to give priority to the extension when the functionality already exists and is overwritten or extended as in the case of the namespace resolver separator symbol `|`. However that will not change the standard nature of the project and I will be happy to rearrange the code if necessary.

So definitely the choice is your !

**Comment by dperini** [comment]
The support for namespace values and attribute presence was recently reviewed and fixed.
Support for the last Selector Level 4 spec should be complete.
I am willing to add code if necessary, better if it can be added as a module.
Not an issue in the current implementation. Closing this.

**Comment by bedney** [comment]
Thanks for working on this but I just pulled the latest source and tried it.

It fails to pass the following, relatively simple, DOM namespace test:

```
docStr = '<foo:bar xmlns:foo="www.foo.com">Hi</foo:bar>';
dom = (new DOMParser()).parseFromString(docStr, 'application/xml');
```

```
NW.Dom.select('*', dom) -> [<element>] (as expected)
NW.Dom.select('foo|bar', dom) -> [] (this should have the element in it as well)
NW.Dom.select('*|bar', dom) -> [] (as should this)
NW.Dom.select('bar|bar', dom) -> (throws exception - should be empty []) 
```

Should I file a separate bug for this?

**Comment by dperini** [comment]
@bedney yes please, a separate issue is better.

Until then, a few question to help me understand which of the cases are currently unsupported.
I wrote the allowed values for a namespace and the possible combinations with a tag name.

I have tested that "querySelectorAll" throws exceptions in two of the instances down here.
I tested with latest Firefox. Is that correct ?

Both nwsapi and qsa throw on 'bar|bar'.
Isn't that due to an attempt to access an undefined namespace ?

========================================

namespace allowed values:
  *
  null
  undefined
  string [-a-zA-Z09]

docStr = '<foo:bar xmlns:foo="www.foo.com">Hi</foo:bar>';
dom = (new DOMParser()).parseFromString(docStr, 'application/xml');

// any element with any namespace
console.log( NW.Dom.select('*', dom) );
console.log( dom.querySelectorAll('*') );

// bar element with a namespace ('foo')
console.log( NW.Dom.select('foo|bar', dom) );
//console.log( dom.querySelectorAll('foo|bar') ); // -> error

// bar element with no namespace ('|' absent)
console.log( NW.Dom.select('bar', dom) );
console.log( dom.querySelectorAll('bar') );

// bar element with any namespace ('*')
console.log( NW.Dom.select('*|bar', dom) );
console.log( dom.querySelectorAll('*|bar') );

// bar element with empty namespace ('|' present)
console.log( NW.Dom.select('|bar', dom) );
console.log( dom.querySelectorAll('|bar') );

// bar element with the 'bar' namespace (undefined)
//console.log( NW.Dom.select('bar|bar', dom) ); // -> error
//console.log( dom.querySelectorAll('bar|bar') ); // -> error

Thank you for the report and the help you can give.

**Comment by bedney** [comment]
@dperini -

Yes, you are correct. The calls should throw on `bar|bar` - I was mistaken. I've updated my 4 queries here:

```
NW.Dom.select('*', dom) -> [<element>] (as expected)
NW.Dom.select('foo|bar', dom) -> [] (this should have the element in it as well)
NW.Dom.select('*|bar', dom) -> [] (as should this)
NW.Dom.select('bar|bar', dom) -> (throws exception - this is correct as `bar` is an undefined namespace) 
```

That leaves #2 and #3 from the list above:

`NW.Dom.select('foo|bar', dom)` -> should return an Array with 1 element. This is a query that matches exactly the namespace prefix and the element name.

`NW.Dom.select('*|bar', dom)` -> should return an Array with 1 element. This is a query that matches **any** namespace prefix and the element name.

Currently, QSA itself supports `*|bar`, but does not support `foo|bar` because it is not currently truly 'namespace aware'. It has been promised in some future version (v2) of the `querySelector/querySelectorAll/matches` W3C DOM API.

This is a portion of the functionality that I would like NWSAPI to polyfill. The other portion was supplying a 'namespace resolved' Function that would allow you to resolve different prefixes against the same namespace URI. It is important to remember that namespaces really are URIs - the prefixes are merely shorthand.

But I'll file a separate bug with test cases, since that's a much more involved discussion.

**Comment by dperini** [comment]
@bedney thank you for the time and the answers.
This made me understand and clear up a few doubt I had.
I will try to make the basic functionalities work in "nwsapi" at least emulate current browsers behavior with namespaces which by the way also meets 'jsdom' requirements for their selector engine. It will not be immediate but I will take the challenge. Submit a new issue with these bugs.
