### ISSUE TITLE
Case insensitivity is not always handled correctly for attribute selectors

### ISSUE THREAD

**Issue by ypapouski** [dperini/nwsapi#60]
The following attribute selector `[name=abci]` is compiled into `if(((/^abc$/i).test(...)...` that is obviously incorrect. The correct variant is `if(((/^abci$/).test(...)...`.

The possible fix is located in my fork of your library: https://github.com/dperini/nwsapi/pull/59.

**Comment by dperini** [comment]
It wasn't an easy revert but should be OK now.
Thank you anyway for your help & support.

**Comment by dperini** [comment]
The fix as been tested and works with all tests passing (including web_platform_tests).

**Comment by domenic** [comment]
Hi @dperini, any progress on getting this fixed and released to npm? The latest release on npm is still 2.2.1, which has the bug.

**Comment by dperini** [comment]
@domenic / @ypapouski 
this is going to be fixed in  the net couple of days.
Sorry for the delay with this, please just help me decide on the following simplification.
Could we fix tag case-sensitivity by turning the complete input to lowercase ?

HTML_DOCUMENT && (selectors = selectors.toLowerCase());

This could also lead to speed improvements by removing sparse case conversions and conditional cases I have in place throughout the complete code.

Thank you both for the suggestion you can provide.

**Comment by domenic** [comment]
That seems wrong. E.g. `[foo="bar"]` and `[foo="BAR"]` are very different selectors.

**Comment by dperini** [comment]
@ypapouski @domenic 
please check release 2.2.2 on npm.
